sudo: required
services:
  - docker  
before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script: docker exec -it emscripten make -f ./Makefile.travis

deploy:
  - provider: script
    script: bash .travis_publish
    on:
      branch: master