sudo: required
services:
  - docker  
before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script: docker exec -it emscripten make -f ./Makefile.travis

deploy:
  provider: pages
  repo: try-rookie
  target-branch: master
  local-dir: www/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    